[workspace.package]
edition = "2021"
version = "2.0.0-rc.1.0"
# TODO: teams are being deprecated update the authors URL
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]

license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "default_executor",
    "create_nft_for_every_user_trigger",
    "mint_rose_trigger",
    "mint_rose_trigger_args",
    "executor_with_admin",
    "executor_with_custom_permission",
    "executor_with_custom_parameter",
    "executor_remove_permission",
    "executor_with_migration_fail",
    "executor_custom_instructions_simple",
    "executor_custom_instructions_complex",
    "executor_custom_data_model",
    "query_assets_and_save_cursor",
    "smart_contract_can_filter_queries",
    "multisig_register",
    "multisig",
]

[profile.dev]
panic = "abort"

[profile.release]
strip = "debuginfo" # Remove debugging info from the binary
panic = "abort"     # Panics are transcribed to Traps when compiling for wasm anyways
lto = true          # Link-time-optimization produces notable decrease in binary size
opt-level = "z"     # Optimize for size vs speed with "s"/"z"(removes vectorization)
codegen-units = 1   # Further reduces binary size but increases compilation time

[workspace.dependencies]
executor_custom_data_model = { path = "executor_custom_data_model" }

iroha_smart_contract = { version = "=2.0.0-rc.1.0", path = "../smart_contract", features = ["debug"] }
iroha_trigger = { version = "=2.0.0-rc.1.0", path = "../smart_contract/trigger", features = ["debug"] }
iroha_executor = { version = "=2.0.0-rc.1.0", path = "../smart_contract/executor", features = ["debug"] }
iroha_schema = { version = "=2.0.0-rc.1.0", path = "../schema" }
iroha_data_model = { version = "=2.0.0-rc.1.0", path = "../data_model", default-features = false }
iroha_executor_data_model = { version = "=2.0.0-rc.1.0", path = "../smart_contract/executor/data_model" }

parity-scale-codec = { version = "3.2.1", default-features = false }
anyhow = { version = "1.0.71", default-features = false }
serde = { version = "1.0.151", default-features = false }
serde_json = { version = "1.0.91", default-features = false }
getrandom = { version = "0.2", features = ["custom"] }
nonzero_ext = { version = "0.3.0", default-features = false }

dlmalloc = { version = "0.2.6", features = ["global"] }
panic-halt = "0.2.0"
