[package]
name = "iroha_config_base"
version = "2.0.0-pre-rc.9"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[dependencies]
iroha_config_derive = { path = "derive" }

serde = { version = "1.0.142", default-features = false, features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
crossbeam = "0.8.2"
