[package]
name = "iroha_config_base"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_config_derive = { workspace = true }
iroha_crypto = { workspace = true, features = ["std"] }

serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
json5 = { workspace = true }
thiserror = { workspace = true }
displaydoc = { workspace = true }
crossbeam = { workspace = true }
eyre = { workspace = true }

