[package]
name = "iroha_derive"
version = "0.1.0"
authors = ["Nikita Puzankov <humb1t@yandex.ru>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
iroha_macro = { path="../" }
parity-scale-codec = { version = "1.3", features = ["derive"] }
syn = {version = "1.0", features = ["parsing", "full"] }
quote = "1.0"
log = { version = "0.4", features = ["std", "serde"] }
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
iroha_logger = { version = "=0.1.0", path = "../../iroha_logger"}
trybuild = "1.0"
