[package]
name = "iroha_network"
version = "0.1.0"
authors = [ "Nikita Puzankov <humb1t@yandex.ru>", "Egor Ivkov < <e.o.ivkov@gmail.com>", "Vladislav Markushin <negigic@gmail.com>", "武宮誠 <takemiya@soramitsu.co.jp>" ]
edition = "2018"
description = "Iroha Network is built on top Rust STD entities (like Stream) and implements protocol for network peer to peer and client-server communications."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha"]
categories = ["cryptography::cryptocurrencies", "network-programming"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
mock = []

[dependencies]
iroha_derive = { path = "../iroha_macro/iroha_derive" }
async-std = { version = "=1.6.2", features = ["attributes", "unstable"] }
parity-scale-codec = { version = "1.3", features = ["derive"] }
log = "0.4.8"
