[package]
name = "iroha_primitives"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["iroha_macro/std", "fixnum/std", "thiserror"]
# Expose FFI API for dynamic linking (only applicable if crate-type = "cdylib")
ffi-export = ["std", "iroha_ffi"]
# Replace structures and methods with FFI equivalents to facilitate dynamic linkage (mainly used in smartcontracts)
#ffi-import = ["iroha_ffi"]

[dependencies]
iroha_macro = { path = "../macro", version = "=2.0.0-pre-rc.13", default-features = false }
iroha_schema = { path = "../schema", version = "=2.0.0-pre-rc.13", default-features = false }
iroha_ffi = { path = "../ffi", version = "=2.0.0-pre-rc.13", optional = true }

parity-scale-codec = { version = "3.2.1", default-features = false, features = ["derive"] }
fixnum = { version = "0.9.1", default-features = false, features = ["serde", "parity", "i64"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display", "from", "as_ref", "as_mut", "deref", "constructor", "into_iterator"] }
serde = { version = "1.0.151", default-features = false, features = ["derive"] }
smallvec = { version = "1.10.0", default-features = false, features = ["serde", "union"] }
smallstr = { version = "0.3.0", default-features = false, features = ["serde", "union"] }
thiserror = { version = "1.0.38", optional = true }


[dev-dependencies]
serde_json = { version = "1.0.91", default-features = false, features = ["alloc"] }
trybuild = "1.0.73"
