[package]
name = "iroha_primitives"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["iroha_macro/std", "fixnum/std", "thiserror"]
# Replace structures and methods with FFI equivalents to facilitate dynamic linkage (mainly used in smartcontracts)
#ffi_import = ["iroha_ffi"]

# Expose FFI API for dynamic linking (Internal use only)
ffi_export = ["std", "iroha_ffi"]

[dependencies]
iroha_macro = { workspace = true }
iroha_schema = { workspace = true }
iroha_ffi = { workspace = true, optional = true }
iroha_primitives_derive = { workspace = true }

parity-scale-codec = { workspace = true, features = ["derive"] }
fixnum = { workspace = true, features = ["serde", "parity", "i64"] }
derive_more = { workspace = true, features = ["display", "from", "as_ref", "as_mut", "deref", "constructor", "into_iterator"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["macros"] }
smallvec = { version = "1.10.0", default-features = false, features = ["serde", "union"] }
smallstr = { version = "0.3.0", default-features = false, features = ["serde", "union"] }
thiserror = { workspace = true, optional = true }


[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }
trybuild = { workspace = true }
