[package]
name = "iroha_version"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[features]
default = ["std", "derive", "scale", "json"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html.
std = ["iroha_macro/std", "parity-scale-codec/std", "thiserror"]
# Enable macros for versioning
derive = ["iroha_version_derive"]
# Support SCALE codec for encoding and decoding
scale = ["parity-scale-codec/full"]
# Support JSON (de)serialisation
json = ["serde", "serde_json"]
# Enable API for HTTP requests. Should be activated for HTTP clients
http = ["std", "warp"]

[dependencies]
iroha_version_derive = { workspace = true, optional = true }
iroha_macro = { workspace = true }

parity-scale-codec = { workspace = true, optional = true, features = ["derive"] }
serde_json = { workspace = true, optional = true, features = ["alloc"] }
serde = { workspace = true, optional = true, features = ["derive"] }
thiserror = { workspace = true, optional = true }
warp = { workspace = true, optional = true }

[dev-dependencies]
iroha_data_model = { workspace = true }
iroha_logger = { workspace = true }
