[package]
name = "iroha_version"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[features]
default = ["std", "derive", "scale", "json"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html.
std = ["iroha_macro/std", "parity-scale-codec/std", "thiserror"]
# Enable macros for versioning
derive = ["iroha_version_derive"]
# Support SCALE codec for encoding and decoding
scale = ["parity-scale-codec/full"]
# Support JSON (de)serialisation
json = ["serde", "serde_json"]

[dependencies]
iroha_version_derive = { version = "=2.0.0-pre-rc.13", path = "derive", default-features = false, optional = true }
iroha_macro = { version = "=2.0.0-pre-rc.13", path = "../macro", default-features = false }
iroha_schema = { version = "=2.0.0-pre-rc.13", path = "../schema", default-features = false }

parity-scale-codec = { version = "3.2.1", default-features = false, optional = true, features = ["derive"] }
serde_json = { version = "1.0.91", default-features = false, optional = true, features = ["alloc"] }
serde = { version = "1.0.151", default-features = false, optional = true, features = ["derive"] }
thiserror = { version = "1.0.38", default-features = false, optional = true }
warp = { version = "0.3.3", default-features = false, optional = true }

[dev-dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../data_model" }
iroha_logger = { version = "=2.0.0-pre-rc.13", path = "../logger" }
