[package]
name = "iroha_version"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "derive", "scale", "json"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["iroha_macro/std", "parity-scale-codec/std", "thiserror"]
derive = ["iroha_version_derive"]
scale = ["parity-scale-codec/full"]
json = ["serde", "serde_json"]

[dependencies]
iroha_version_derive = { version = "=2.0.0-pre-rc.4", path = "derive", default-features = false, optional = true }
iroha_macro = { version = "=2.0.0-pre-rc.4", path = "../macro", default-features = false }
iroha_schema = { version = "=2.0.0-pre-rc.4", path = "../schema", default-features = false }

parity-scale-codec = { version = "2.3.1", default-features = false, optional = true, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, optional = true, features = ["alloc"] }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
thiserror = { version = "1.0.28", default-features = false, optional = true }
warp = { version = "0.3.2", default-features = false, optional = true }
