[package]
name = "iroha_version"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["scale", "json", "derive"]
scale = ["parity-scale-codec"]
json = ["serde_json"]
derive = ["iroha_version_derive"]

[dependencies]
iroha_version_derive = { path = "derive", optional = true }
iroha_macro = { path = "../macro" }

eyre = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0", optional = true }
thiserror = "1.0.28"

parity-scale-codec = { version = "2", features = ["derive"], optional = true }
warp = { version = "0.3", default-features = false, optional = true }
