version: "3.8"
services:
  iroha0:
    image: hyperledger/iroha2:lts
    platform: linux/amd64
    environment:
      TORII_P2P_ADDR: iroha0:1337
      TORII_API_URL: iroha0:8080
      TORII_TELEMETRY_URL: iroha0:8180
      IROHA_PUBLIC_KEY: "ed01201C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "282ED9F3CF92811C3818DBC4AE594ED59DC1A2F78E4241E31924E101D6B1FB831C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"}, {"address":"iroha1:1338", "public_key": "ed0120CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"}, {"address": "iroha2:1339", "public_key": "ed0120FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"}, {"address": "iroha3:1340", "public_key": "ed01208E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203F4E3E98571B55514EDC5CCF7E53CA7509D89B2868E62921180A6F57C2F4E255'
      IROHA_GENESIS_ACCOUNT_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "038AE16B219DA35AA036335ED0A43C28A2CC737150112C78A7B8034B9D99C9023F4E3E98571B55514EDC5CCF7E53CA7509D89B2868E62921180A6F57C2F4E255"}'
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
    ports:
      - "1337:1337"
      - "8080:8080"
      - "8180:8180"
    volumes:
      - './configs/peer/lts:/config'
    init: true
    command: iroha --submit-genesis

  iroha1:
    image: hyperledger/iroha2:lts
    platform: linux/amd64
    environment:
      TORII_P2P_ADDR: iroha1:1338
      TORII_API_URL: iroha1:8081
      TORII_TELEMETRY_URL: iroha1:8181
      IROHA_PUBLIC_KEY: "ed0120CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "3BAC34CDA9E3763FA069C1198312D1EC73B53023B8180C822AC355435EDC4A24CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"}, {"address":"iroha1:1338", "public_key": "ed0120CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"}, {"address": "iroha2:1339", "public_key": "ed0120FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"}, {"address": "iroha3:1340", "public_key": "ed01208E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203F4E3E98571B55514EDC5CCF7E53CA7509D89B2868E62921180A6F57C2F4E255'
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
    ports:
      - "1338:1338"
      - "8081:8081"
      - "8181:8181"
    volumes:
      - './configs/peer/lts:/config'
    init: true

  iroha2:
    image: hyperledger/iroha2:lts
    platform: linux/amd64
    environment:
      TORII_P2P_ADDR: iroha2:1339
      TORII_API_URL: iroha2:8082
      TORII_TELEMETRY_URL: iroha2:8182
      IROHA_PUBLIC_KEY: "ed0120FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "1261A436D36779223D7D6CF20E8B644510E488E6A50BAFD77A7485264D27197DFACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"}, {"address":"iroha1:1338", "public_key": "ed0120CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"}, {"address": "iroha2:1339", "public_key": "ed0120FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"}, {"address": "iroha3:1340", "public_key": "ed01208E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203F4E3E98571B55514EDC5CCF7E53CA7509D89B2868E62921180A6F57C2F4E255'
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
    ports:
      - "1339:1339"
      - "8082:8082"
      - "8182:8182"
    volumes:
      - './configs/peer/lts:/config'
    init: true

  iroha3:
    image: hyperledger/iroha2:lts
    platform: linux/amd64
    environment:
      TORII_P2P_ADDR: iroha3:1340
      TORII_API_URL: iroha3:8083
      TORII_TELEMETRY_URL: iroha3:8183
      IROHA_PUBLIC_KEY: "ed01208E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "A70DAB95C7482EB9F159111B65947E482108CFE67DF877BD8D3B9441A781C7C98E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha0:1337", "public_key": "ed01201C61FAF8FE94E253B93114240394F79A607B7FA55F9E5A41EBEC74B88055768B"}, {"address":"iroha1:1338", "public_key": "ed0120CC25624D62896D3A0BFD8940F928DC2ABF27CC57CEFEB442AA96D9081AAE58A1"}, {"address": "iroha2:1339", "public_key": "ed0120FACA9E8AA83225CB4D16D67F27DD4F93FC30FFA11ADC1F5C88FD5495ECC91020"}, {"address": "iroha3:1340", "public_key": "ed01208E351A70B6A603ED285D666B8D689B680865913BA03CE29FB7D13A166C4E7F1F"}]'
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: 'ed01203F4E3E98571B55514EDC5CCF7E53CA7509D89B2868E62921180A6F57C2F4E255'
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
    ports:
      - "1340:1340"
      - "8083:8083"
      - "8183:8183"
    volumes:
      - './configs/peer/lts:/config'
    init: true
