version: "3.3"
services:
  iroha:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    image: iroha:debug
    environment:
      TORII_P2P_URL: iroha:1337
      TORII_API_URL: iroha:8080
      TORII_CONNECT_URL: iroha:8888
      MAX_FAULTY_PEERS: 0
      IROHA_ROOT_PUBLIC_KEY: "ed207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
      IROHA_PUBLIC_KEY: 'ed207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0'
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "9ac47abf59b356e0bd7dcbbbb4dec080e302156a48ca907e47cb6aea1d32719e7233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"}'
      IROHA_TRUSTED_PEERS: '[{"address":"iroha:1337", "public_key": "ed207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"}]'
    ports:
      - "1337:1337"
      - "8888:8888"
      - "8080:8080"
