# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
deny = [
    'anonymous_parameters',
    'clippy::all',
    'clippy::dbg_macro',
    'clippy::nursery',
    'clippy::pedantic',
    'clippy::restriction',
    'future_incompatible',
    'missing_copy_implementations',
    'missing_docs',
    'nonstandard_style',
    'private_doc_tests',
    'rust_2018_idioms',
    'trivial_casts',
    'trivial_numeric_casts',
    'unconditional_recursion',
    'unsafe_code',
    'unused',
    'unused_import_braces',
    'variant_size_differences',
]

allow = [
    'clippy::string_add',
    'unknown_lints',
    'clippy::as_conversions',
    'clippy::else_if_without_else',
    'clippy::enum_glob_use',
    'clippy::exhaustive_enums',
    'clippy::exhaustive_structs',
    'clippy::implicit_return',
    'clippy::inconsistent_struct_constructor',
    'clippy::indexing_slicing',
    'clippy::integer_arithmetic',
    'clippy::let_underscore_must_use',
    'clippy::match_wildcard_for_single_variants',
    'clippy::missing_docs_in_private_items',
    # Not all public items should be inline. We only inline **trivial** functions.
    'clippy::missing_inline_in_public_items',
    'clippy::module_name_repetitions',
    'clippy::must_use_candidate',
    'clippy::pattern_type_mismatch',
    'clippy::semicolon_if_nothing_returned',
    'clippy::shadow_reuse',
    'clippy::shadow_same',
    'clippy::unreachable',
    'clippy::use_self',
    'clippy::wildcard_enum_match_arm',
    'clippy::wildcard_imports',
    'elided_lifetimes_in_paths',
    # Our preferred style.
    'clippy::non-ascii-literal',
    'clippy::mod-module-files',
    'clippy::separated-literal-suffix',
    # Most trybuild code triggers a false-positive.
    'clippy::self-named-module-files',
    # We often need to shadow the name of the method to specialise.
    # As soon as trait specialisation is stable we need to remove it.
    'clippy::same_name_method',
    'clippy::pub_use',

    # TODO: Remove when stabilized
    ## https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn
    'clippy::missing_const_for_fn'
]

warn = []
