#
# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
#
deny = [
    'anonymous_parameters',
    'clippy::all',
    'clippy::dbg_macro',
    'clippy::nursery',
    'clippy::pedantic',
    'clippy::restriction',
    'future_incompatible',
    'missing_copy_implementations',
    'missing_debug_implementations',
    'missing_docs',
    'nonstandard_style',
    'private_doc_tests',
    'rust_2018_idioms',
    'trivial_casts',
    'trivial_numeric_casts',
    'unsafe_code',
    'unused',
    'unused_import_braces',
    'unused_results',
    'variant_size_differences',
]
allow = [
    'clippy::as_conversions',
    'clippy::enum_glob_use',
    'clippy::exhaustive_enums',
    'clippy::exhaustive_structs',
    'clippy::implicit_return',
    'clippy::indexing_slicing',
    'clippy::integer_arithmetic',
    'clippy::let_underscore_must_use',
    'clippy::match_wildcard_for_single_variants',
    'clippy::missing_docs_in_private_items',
    'clippy::missing_inline_in_public_items',
    'clippy::must_use_candidate',
    'clippy::pattern_type_mismatch',
    'clippy::shadow_reuse',
    'clippy::shadow_same',
    'clippy::unreachable',
    'clippy::use_self',
    'clippy::wildcard-enum-match-arm',
    'clippy::wildcard_imports',
    'elided_lifetimes_in_paths',
]
warn = []
