[package]
name = "iroha_schema_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
iroha_schema = { workspace = true}

trybuild = { workspace = true }
