[package]
name = "iroha_actor"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
deadlock_detection = ["petgraph"]

[dependencies]
async-trait = "0.1"
once_cell = "1.8.0"
dashmap = "4"
eyre = "0.6.5"
futures = { version = "0.3.17", default-features = false, features = ["std", "async-await"] }
iroha_actor_derive = { path = "derive" }
tokio = { version = "1.6.0", features = ["sync", "time", "rt", "io-util", "rt-multi-thread"]}
iroha_logger = { path = "../logger" }
thiserror = "1.0.28"

petgraph = { version = "0.5", optional = true }

[dev-dependencies]
trybuild = "1"
tokio = { version = "1.6.0", features = ["macros"]}
