[package]
name = "iroha_torii"

edition.workspace = true
version.workspace = true
authors.workspace = true

description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
# Enables Telemetry (i.e. Status, Metrics, and API Version) endpoints
telemetry = ["iroha_telemetry", "iroha_core/telemetry", "serde_json"]
# Enables profiling endpoint
profiling = ["pprof"]
# Enables Data Model Schema endpoint
schema = ["iroha_schema", "iroha_schema_gen"]

[dependencies]
iroha_core = { workspace = true }
iroha_config = { workspace = true }
iroha_primitives = { workspace = true }
iroha_logger = { workspace = true }
iroha_data_model = { workspace = true, features = ["http"] }
iroha_version = { workspace = true }
iroha_torii_const = { workspace = true }
iroha_futures = { workspace = true }
iroha_macro = { workspace = true }
iroha_schema = { workspace = true, optional = true }
iroha_schema_gen = { workspace = true, optional = true }
iroha_telemetry = { workspace = true, optional = true }

thiserror = { workspace = true }
displaydoc = { workspace = true }
futures = { workspace = true, features = ["std", "async-await"] }
axum = { workspace = true, features = ["multipart", "ws", "query", "json", "tokio", "http1"] }
tower-http = { version = "0.5.0", features = ["trace", "timeout"] }
tokio = { workspace = true, features = ["sync", "time", "macros"] }
eyre = { workspace = true }
error-stack = { workspace = true, features = ["eyre"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
async-trait = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
# TODO: switch to original crate once fix is merged (https://github.com/tikv/pprof-rs/pull/241)
pprof = { git = " https://github.com/Erigara/pprof-rs", branch = "fix_pointer_align", optional = true, default-features = false, features = ["protobuf-codec", "frame-pointer", "cpp"] }
nonzero_ext = { workspace = true }
pretty-error-debug = "0.3.0"

[dev-dependencies]
http-body-util = "0.1.2"
