[package]
name = "iroha_p2p"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true
categories = ["network-programming"]

[lints]
workspace = true

[dependencies]
iroha_logger = { workspace = true }
iroha_crypto = { workspace = true, default-features = true }
iroha_data_model = { workspace = true, default-features = true, features = ["transparent_api"] }
iroha_primitives = { workspace = true }
iroha_config = { workspace = true }
iroha_data_model_derive = { workspace = true }

rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-util", "net", "time"] }
futures = { workspace = true, features = ["alloc"] }
async-trait = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
displaydoc = { workspace = true }
derive_more = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
iroha_config_base = { workspace = true }
test_network = { workspace = true }
