[package]
name = "iroha_p2p"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true
categories = ["network-programming"]

[dependencies]
iroha_logger = { version = "=2.0.0-pre-rc.13", path = "../logger" }
iroha_crypto = { version = "=2.0.0-pre-rc.13", path = "../crypto" }
iroha_actor = { version = "=2.0.0-pre-rc.13", path = "../actor" }
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../data_model" }
iroha_config_base = { version = "=2.0.0-pre-rc.13", path = "../config/base" }
iroha_data_model_derive = { version = "=2.0.0-pre-rc.13", path = "../data_model/derive" }

rand = "0.8.5"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros"] }
async-stream = "0.3.3"
futures = { version = "0.3.25", default-features = false }
async-trait = "0.1.60"
parity-scale-codec = { version = "3.2.1", features = ["derive"] }
aead = "0.3.2"
thiserror = "1.0.38"
derive_more = "0.99.17"

[dev-dependencies]
test_network = { version = "=2.0.0-pre-rc.13", path = "../core/test_network" }
