[package]
name = "iroha_p2p"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true
categories = ["network-programming"]

[dependencies]
iroha_logger = { workspace = true }
iroha_crypto = { workspace = true }
iroha_data_model = { workspace = true }
iroha_primitives = { workspace = true }
iroha_config_base = { workspace = true }
iroha_data_model_derive = { workspace = true }

rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-util", "net"] }
async-stream = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
async-trait = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
aead = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
test_network = { workspace = true }
