[package]
name = "iroha_futures_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[features]
default = ["telemetry"]
# Support lightweight telemetry, including diagnostics
telemetry = []

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["default", "full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-error = { workspace = true }
