[package]
name = "iroha"

edition.workspace = true
version.workspace = true
authors.workspace = true

description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["bridge", "telemetry", "schema-endpoint"]

# Support interoperability with popular blockchain networks (Substrate, Ether, etc.)
bridge = ["iroha_core/bridge"]
# Support Decentralised Exchange, including functionality for atomic exchange instruction
dex = ["iroha_core/dex"]
# Support lightweight telemetry, including diagnostics
telemetry = ["iroha_telemetry", "iroha_core/telemetry"]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = ["iroha_core/dev-telemetry", "iroha_telemetry"]
# Support schema generation from the `schema` endpoint in the local binary.
# Useful for debugging issues with decoding in SDKs.
schema-endpoint = ["iroha_schema_gen"]
# Support internal testing infrastructure for integration tests.
# Disable in production.
test-network = ["thread-local-panic-hook"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_core = { version = "=2.0.0-pre-rc.13", path = "../core" }
iroha_macro = { version = "=2.0.0-pre-rc.13", path = "../macro" }
iroha_logger = { version = "=2.0.0-pre-rc.13", path = "../logger" }
iroha_futures = { version = "=2.0.0-pre-rc.13", path = "../futures" }
iroha_actor = { version = "=2.0.0-pre-rc.13", path = "../actor" }
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../data_model", features = ["transparent_api", "http"] }
iroha_telemetry = { version = "=2.0.0-pre-rc.13", path = "../telemetry", optional = true }
iroha_version = { version = "=2.0.0-pre-rc.13", path = "../version", features = ["http"] }
iroha_config = { version = "=2.0.0-pre-rc.13", path = "../config" }
iroha_crypto = { version = "=2.0.0-pre-rc.13", path = "../crypto" }
iroha_p2p = { version = "=2.0.0-pre-rc.13", path = "../p2p" }
iroha_schema_gen = { version = "=2.0.0-pre-rc.13", path = "../schema/gen", optional = true }
iroha_cli_derive = { version = "=2.0.0-pre-rc.13", path = "derive" }
iroha_genesis = { version = "=2.0.0-pre-rc.13", path = "../genesis" }

async-trait = "0.1.60"
color-eyre = "0.6.2"
eyre = "0.6.8"
futures = { version = "0.3.25", default-features = false, features = ["std", "async-await"] }
parity-scale-codec = { version = "3.2.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "macros", "fs", "signal"] }
warp = "0.3.3"
serial_test = "0.8.0"
once_cell = "1.16.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
supports-color = "2.0.0"
thread-local-panic-hook = { version = "0.1.0", optional = true }

[build-dependencies]
iroha_wasm_builder = { version = "=2.0.0-pre-rc.13", path = "../wasm_builder" }

eyre = "0.6.8"
vergen = { version = "7.4.2", default-features = false, features = ["cargo"] }

[package.metadata.cargo-all-features]
denylist = [
"bridge",
"dex",
"schema-endpoint",
"telemetry",
"test-network"
] # TODO: remove `dex` and `bridge` once there's code for them.
skip_optional_dependencies = true
