[package]
name = "iroha"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha is a straightforward distributed ledger technology (DLT), inspired by Japanese Kaizen principle â€” eliminate excessiveness (muri). Iroha has essential functionality for your asset, information and identity management needs, at the same time being an efficient and trustworthy crash fault-tolerant tool for your enterprise needs."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger"]
categories = ["cryptography::cryptocurrencies"]

[features]
default = ["bridge", "telemetry", "schema-endpoint"]

# Support interoperability with popular blockchain networks (Substrate, Ether, etc.)
bridge = ["iroha_core/bridge"]
# Support Decentralised Exchange, including functionality for atomic exchange instruction
dex = ["iroha_core/dex"]
# Support lightweight telemetry, including diagnostics
telemetry = ["iroha_telemetry", "iroha_core/telemetry"]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = ["iroha_core/dev-telemetry", "iroha_telemetry"]
# Support schema generation from the `schema` endpoint in the local binary.
# Useful for debugging issues with decoding in SDKs.
schema-endpoint = ["iroha_schema_gen"]
# Support internal testing infrastructure for integration tests.
# Disable in production.
test-network = []

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_core = { version = "=2.0.0-pre-rc.7", path = "../core" }
iroha_macro = { version = "=2.0.0-pre-rc.7", path = "../macro" }
iroha_permissions_validators = { version = "=2.0.0-pre-rc.7", path = "../permissions_validators" }
iroha_logger = { version = "=2.0.0-pre-rc.7", path = "../logger" }
iroha_futures = { version = "=2.0.0-pre-rc.7", path = "../futures" }
iroha_actor = { version = "=2.0.0-pre-rc.7", path = "../actor" }
iroha_data_model = { version = "=2.0.0-pre-rc.7", path = "../data_model" }
iroha_telemetry = { version = "=2.0.0-pre-rc.7", path = "../telemetry", optional = true }
iroha_version = { version = "=2.0.0-pre-rc.7", path = "../version", features = ["warp"] }
iroha_config = { version = "=2.0.0-pre-rc.7", path = "../config" }
iroha_crypto = { version = "=2.0.0-pre-rc.7", path = "../crypto" }
iroha_p2p = { version = "=2.0.0-pre-rc.7", path = "../p2p" }
iroha_schema_gen = { version = "=2.0.0-pre-rc.7", path = "../schema/gen", optional = true }
iroha_cli_derive = { version = "=2.0.0-pre-rc.7", path = "derive" }

async-trait = "0.1.57"
color-eyre = "0.6.2"
eyre = "0.6.8"
futures = { version = "0.3.21", default-features = false, features = ["std", "async-await"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "macros", "fs", "signal"] }
warp = "0.3.2"
serial_test = "0.8.0"

[dev-dependencies]
test_network = { version = "=2.0.0-pre-rc.7", path = "../core/test_network" }

[package.metadata.cargo-all-features]
denylist = [
"bridge",
"dex",
"schema-endpoint",
"telemetry",
"test-network"
] # TODO: remove `dex` and `bridge` once there's code for them.
skip_optional_dependencies = true
