[package]
name = "iroha"
version = "2.0.0-pre.1"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha is a straightforward distributed ledger technology (DLT), inspired by Japanese Kaizen principle â€” eliminate excessiveness (muri). Iroha has essential functionality for your asset, information and identity management needs, at the same time being an efficient and trustworthy crash fault-tolerant tool for your enterprise needs."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger"]
categories = ["cryptography::cryptocurrencies"]

[features]
bridge = ["iroha_core/bridge"]
dex = ["iroha_core/dex"]
roles = ["iroha_core/roles", "iroha_permissions_validators/roles"]
telemetry = ["iroha_core/telemetry"]
dev-telemetry = ["iroha_core/dev-telemetry"]
default = ["bridge"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_core = { version = "=2.0.0-pre.1", path = "../core" }
iroha_permissions_validators = { version = "=2.0.0-pre.1", path = "../permissions_validators" }
iroha_logger = { version = "=2.0.0-pre.1", path = "../logger"}

color-eyre = "0.5.11"
tokio = { version = "1.6.0", features = ["rt", "rt-multi-thread"]}
