[package]
name = "iroha_telemetry"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[features]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = []
# Export Prometheus metrics. See https://prometheus.io/.
metric-instrumentation = []

[dependencies]
iroha_config = { workspace = true }
iroha_logger = { workspace = true }
iroha_futures = { workspace = true, features = ["telemetry"] }
iroha_telemetry_derive = { workspace = true }

async-trait = { workspace = true }
chrono = "0.4.31"
eyre = { workspace = true }
futures = { workspace = true, features = ["std", "async-await"] }
serde_json = { workspace = true }
streaming-stats = "0.2.3"
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = { workspace = true, features = ["fs", "sync"] }
tokio-tungstenite = { workspace = true }
url = { workspace = true, features = ["serde"] }
prometheus = { workspace = true }
parity-scale-codec = { workspace = true }

[build-dependencies]
eyre = { workspace = true }
vergen = { workspace = true, features = ["cargo", "git", "gitoxide"] }

[dev-dependencies]
expect-test = { workspace = true }
hex = { workspace = true }

