[package]
name = "iroha_telemetry"
version = "2.0.0-pre-rc.13"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
build = "build.rs"

[features]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = []
# Export Prometheus metrics. See https://prometheus.io/.
metric-instrumentation = []

[dependencies]
iroha_config = { version = "=2.0.0-pre-rc.13", path = "../config" }
iroha_logger = { version = "=2.0.0-pre-rc.13", path = "../logger" }
iroha_futures = { version = "=2.0.0-pre-rc.13", path = "../futures", features = ["telemetry"] }
iroha_telemetry_derive = { version = "=2.0.0-pre-rc.13", path = "derive" }


async-trait = "0.1.60"
chrono = "0.4.23"
eyre = "0.6.8"
futures = { version = "0.3.25", default-features = false, features = ["std", "async-await"] }
serde_json = "1.0.91"
streaming-stats = "0.2.3"
serde = { version = "1.0.151", features = ["derive"] }
tokio = { version = "1.23.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.11", features = ["fs"] }
tokio-tungstenite = "0.17.2"
url = { version = "2.3.1", features = ["serde"] }
prometheus = { version = "0.13.3", default-features = false }


[build-dependencies]
anyhow = "1.0.68"
vergen = { version = "7.4.2", default-features = false, features = ["cargo", "git"] }
libgit2-sys = {version = "=0.13.4"}

