[package]
name = "iroha_core"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha is a straightforward distributed ledger technology (DLT), inspired by Japanese Kaizen principle â€” eliminate excessiveness (muri). Iroha has essential functionality for your asset, information and identity management needs, at the same time being an efficient and trustworthy crash fault-tolerant tool for your enterprise needs."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger"]
categories = ["cryptography::cryptocurrencies"]

[features]
default = ["bridge", "cli", "telemetry"]

# Interoperability with popular blockchain networks (Substrate, Ether, etc.)
bridge = []
# Support lightweight telemetry, including diagnostics
telemetry = []
# Support the included CLI
cli = []
# Support Decentralised Exchange, including functionality for atomic exchange instruction
dex = []
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = ["telemetry", "iroha_telemetry/dev-telemetry"]
# Support Prometheus metrics. See https://prometheus.io/.
expensive-telemetry = ["iroha_telemetry/metric-instrumentation"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.7", path = "../data_model", features = ["mutable_api", "warp"] }
iroha_macro = { version = "=2.0.0-pre-rc.7", path = "../macro" }
iroha_p2p = { version = "=2.0.0-pre-rc.7", path = "../p2p" }
iroha_logger = { version = "=2.0.0-pre-rc.7", path = "../logger"}
iroha_crypto = { version = "=2.0.0-pre-rc.7", path = "../crypto" }
iroha_version = { version = "=2.0.0-pre-rc.7", path = "../version", features = ["warp"] }
iroha_actor = { version = "=2.0.0-pre-rc.7", path = "../actor" }
iroha_config = { version = "=2.0.0-pre-rc.7", path = "../config" }
iroha_futures = { version = "=2.0.0-pre-rc.7", path = "../futures" }
iroha_telemetry = { version = "=2.0.0-pre-rc.7", path = "../telemetry" }
iroha_schema = { version = "=2.0.0-pre-rc.7", path = "../schema" }
iroha_primitives = { version = "=2.0.0-pre-rc.7", path = "../primitives" }

async-trait = "0.1.57"
async-stream = "0.3.3"
dashmap = "5.3.4"
eyre = "0.6.8"
futures = { version = "0.3.21", default-features = false, features = ["std", "async-await"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
rand = "0.8.5"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.20.1", features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "macros", "fs"] }
tokio-stream = { version = "0.1.9", features = ["fs"] }
crossbeam-queue = "0.3.6"
thiserror = "1.0.32"
pin-project = "1.0.11"
wasmtime = "0.39.1"
byteorder = "1.4.3"

# transitive dependencies
anyhow = "1.0.60"
derive_more = "0.99.17"
getset = "0.1.2"

[dev-dependencies]
tempfile = "3.3.0"
criterion = "0.3.6"
hex = "0.4.3"
byte-unit = "4.0.14"
once_cell = "1.13.0"

[[bench]]
name = "sumeragi"
harness = false

[[bench]]
name = "validation"
harness = false

[[bench]]
name = "kura"
harness = false


[package.metadata.cargo-all-features]
denylist = [
"bridge",
"dex",
"schema-endpoint",
"telemetry",
"test-network"
] # TODO: remove `dex` and `bridge` once there's code for them.
skip_optional_dependencies = true
