[package]
name = "iroha_core"
version = "2.0.0-pre-rc.3"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha is a straightforward distributed ledger technology (DLT), inspired by Japanese Kaizen principle â€” eliminate excessiveness (muri). Iroha has essential functionality for your asset, information and identity management needs, at the same time being an efficient and trustworthy crash fault-tolerant tool for your enterprise needs."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger"]
categories = ["cryptography::cryptocurrencies"]

[features]
bridge = []
dex = []
roles = ["iroha_data_model/roles"]
telemetry = []
cli = []
cross_crate_testing = []
dev-telemetry = ["telemetry", "iroha_telemetry/dev-telemetry"]
expensive-telemetry = ["iroha_telemetry/metric-instrumentation"]
default = ["bridge", "cli", "telemetry", "roles"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.3", path = "../data_model", features = ["mutable_api", "warp"] }
iroha_macro = { version = "=2.0.0-pre-rc.3", path = "../macro" }
iroha_p2p = { version = "=2.0.0-pre-rc.3", path = "../p2p" }
iroha_logger = { version = "=2.0.0-pre-rc.3", path = "../logger"}
iroha_crypto = { version = "=2.0.0-pre-rc.3", path = "../crypto" }
iroha_version = { version = "=2.0.0-pre-rc.3", path = "../version", features = ["warp"] }
iroha_actor = { version = "=2.0.0-pre-rc.3", path = "../actor" }
iroha_config = { version = "=2.0.0-pre-rc.3", path = "../config" }
iroha_futures = { version = "=2.0.0-pre-rc.3", path = "../futures" }
iroha_telemetry = { version = "=2.0.0-pre-rc.3", path = "../telemetry" }
iroha_schema = { version = "=2.0.0-pre-rc.3", path = "../schema" }

async-trait = "0.1"
async-stream = "0.3.2"
dashmap = { version = "4.0" }
eyre = "0.6.5"
futures = { version = "0.3.17", default-features = false, features = ["std", "async-await"] }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.6.0", features = ["sync", "time", "rt", "io-util", "rt-multi-thread", "macros", "fs"]}
tokio-stream = { version = "0.1.6", features = ["fs"]}
crossbeam-queue = "0.3"
warp = "0.3"
thiserror = "1.0.28"
pin-project = "1"
wasmtime = "0.35.1"
color-eyre = "0.5.11"
smallstr = { version = "0.3.0", default-features = false, features = ["serde", "union"] }
smallvec = { version = "1.8.0", features = ["serde", "union"] }

# transitive dependencies
anyhow = ">= 1.0"

[dev-dependencies]
tempfile = "3"
criterion = "0.3"
iroha_data_model = { version = "=2.0.0-pre-rc.3", path = "../data_model", features = ["warp", "cross_crate_testing"] }
hex = "0.4.0"
byte-unit = "4.0.12"
once_cell = "1.8.0"
unique_port = "0.1.0"

[[bench]]
name = "sumeragi"
harness = false

[[bench]]
name = "validation"
harness = false

[[bench]]
name = "kura"
harness = false
