[package]
name = "iroha_trigger"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
# Enables debugging tools such as `dbg()` and `DebugUnwrapExt`
debug = ["iroha_smart_contract/debug"]

[dependencies]
iroha_smart_contract_utils.workspace = true
iroha_smart_contract.workspace = true
iroha_trigger_derive.workspace = true
