[package]
name = "iroha_genesis"
version = "2.0.0-pre-rc.13"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[dependencies]
iroha_config = { version = "=2.0.0-pre-rc.13", path = "../config" }
iroha_crypto = { version = "=2.0.0-pre-rc.13", path = "../crypto" }
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../data_model", features = ["transparent_api"] }
iroha_logger = { version = "=2.0.0-pre-rc.13", path = "../logger" }
iroha_primitives = { version = "=2.0.0-pre-rc.13", path = "../primitives" }
iroha_schema = { version = "=2.0.0-pre-rc.13", path = "../schema" }

derive_more = { version = "0.99.17", default-features = false, features = ["deref"]}
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
eyre = "0.6.8"
