[package]
name = "iroha_futures"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
telemetry = ["iroha_futures_derive/telemetry"]

[dependencies]
iroha_futures_derive = { path = "derive" }
iroha_logger = { path = "../logger" }

rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.6.0", features = ["rt", "rt-multi-thread", "macros"]}

[dev-dependencies]
tokio-stream = { version = "0.1.6" }
