[package]
name = "iroha_validator"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
# Enables debugging tools such as `dbg()` and `DebugUnwrapExt`
debug = ["iroha_wasm/debug"]

[dependencies]
iroha_wasm = { version = "2.0.0-pre-rc.19", path = ".." }
iroha_schema = { path = "../../schema", version = "=2.0.0-pre-rc.19" }
iroha_validator_derive = { version = "2.0.0-pre-rc.19", path = "derive" }

serde = { version = "1.0.151", default-features = false }
serde_json = { version = "1.0.91", default-features = false }

[dev-dependencies]
webassembly-test.workspace = true
