[package]
name = "iroha_schema_gen"
version = "2.0.0-pre-rc.3"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"


[dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.3", path = "../../data_model" }
iroha_core = { version = "=2.0.0-pre-rc.3", path = "../../core"}
iroha_crypto = { version = "=2.0.0-pre-rc.3", path = "../../crypto" }
iroha_schema = { version = "=2.0.0-pre-rc.3", path = "../../schema" }

serde_json = "1"
