[package]
name = "iroha_data_model"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha uses a simple data model made up of domains, peers, accounts, assets, signatories, and permissions. This library contains basic data model structures."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "model"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
default = []
roles = []
test = []

[dependencies]
iroha_crypto = { path = "../crypto" }
iroha_macro = { version = "=0.1.0", path = "../macro" }
iroha_schema = { path = "../schema"}
iroha_version = { version = "=0.1.0", path = "../version", features = ["warp", "derive"] }

eyre = "0.6.5"
fixnum = { version = "0.6", features = ["i64"]}
dashmap = { version = "4.0" }
parity-scale-codec = { version = "2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.28"
prometheus = { version = "0.13.0", default-features = false }

warp = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
iroha_core = { path = "../core" }
iroha_client = { version = "=0.1.0", path = "../client" }

hex-literal = { version = "0.3.4" }
test_network = { path = "../core/test_network" }
tokio = { version = "1.6.0", features = ["rt", "rt-multi-thread"]}
trybuild = "1.0.53"
