[workspace.package]
edition = "2021"
version = "2.0.0-rc.1.0"
# TODO: teams are being deprecated update the authors URL
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]

license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "libs/*",
    "samples/*",
]

[profile.release]
panic = "abort"
overflow-checks = true
debug-assertions = true

[profile.dev]
panic = "abort"

[profile.deploy]
inherits = "release"
overflow-checks = false
debug-assertions = false
strip = "debuginfo" # Remove debugging info from the binary
lto = true          # Link-time-optimization produces notable decrease in binary size
opt-level = "z"     # Optimize for size vs speed with "s"/"z"(removes vectorization)
codegen-units = 1   # Further reduces binary size but increases compilation time

[workspace.dependencies]
iroha_smart_contract = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_smart_contract", features = ["debug"] }
iroha_trigger = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_trigger", features = ["debug"] }
iroha_executor = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_executor", features = ["debug"] }
iroha_schema = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_schema" }

iroha_data_model = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_data_model", default-features = false }
iroha_executor_data_model = { version = "=2.0.0-rc.1.0", path = "../crates/iroha_executor_data_model" }
mint_rose_trigger_data_model = { path = "../data_model/samples/mint_rose_trigger_data_model" }
executor_custom_data_model = { path = "../data_model/samples/executor_custom_data_model" }

parity-scale-codec = { version = "3.2.1", default-features = false }
anyhow = { version = "1.0.71", default-features = false }
serde = { version = "1.0.151", default-features = false }
serde_json = { version = "1.0.91", default-features = false }
nonzero_ext = { version = "0.3.0", default-features = false }

dlmalloc = { version = "0.2.6", features = ["global"] }
panic-halt = "0.2.0"
