[package]
name = "test_network"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# Create a mock query for testing
query = []

[dependencies]
iroha = { path = "../../cli", features = ["test-network"] }
iroha_actor = { version = "=2.0.0-pre-rc.5", path = "../../actor" }
iroha_client = { version = "=2.0.0-pre-rc.5", path = "../../client" }
iroha_core = { version = "=2.0.0-pre-rc.5", path = "../../core" }
iroha_data_model = { version = "=2.0.0-pre-rc.5", path = "../../data_model" }
iroha_logger = { version = "=2.0.0-pre-rc.5", path = "../../logger" }
iroha_permissions_validators = { version = "=2.0.0-pre-rc.5", path = "../../permissions_validators" }

eyre = "0.6.5"
futures = { version = "0.3.17", default-features = false, features = ["std", "async-await"] }
once_cell = "1.8.0"
rand = "0.8"
tempfile = "3"
tokio = { version = "1.6.0", features = ["rt", "rt-multi-thread", "macros"]}
unique_port = "0.2.1"

[dev-dependencies]
async-trait = "0.1"
