[package]
name = "test_network"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha = { workspace = true, features = ["test-network"] }
iroha_client = { workspace = true }
iroha_core = { workspace = true }
iroha_config = { workspace = true }
iroha_data_model = { workspace = true }
iroha_primitives = { workspace = true }
iroha_logger = { workspace = true }
iroha_genesis = { workspace = true }


eyre = { workspace = true }
futures = { workspace = true, features = ["std", "async-await"] }
rand = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
unique_port = "0.2.1"
parity-scale-codec = { version = "3.1.5", default-features = false }
