[package]
name = "iroha_data_model_derive"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = {version = "1", default-features = false, features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
