[package]
name = "iroha_data_model_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.107", features = ["full", "extra-traits"] }
quote = "1.0.23"
proc-macro2 = "1.0.49"
proc-macro-error = "1.0.4"
iroha_macro_utils = { version = "2.0.0-pre-rc.13", path = "../../macro/utils" }
serde_json = "1.0.91"

[dev-dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../", features = ["http"] }

serde = { version = "1.0.151", default-features = false, features = ["derive"] }
serde_json = "1.0.91"
trybuild = "1.0.73"
