[package]
name = "iroha_config_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.107", default-features = false, features = ["derive", "parsing", "proc-macro", "clone-impls", "printing"] }
# This is the maximally compressed set of features. Yes we also need "printing".
quote = "1.0.23"
proc-macro2 = "1.0.49"
proc-macro-error = "1.0.4"

iroha_macro_utils = { version = "=2.0.0-pre-rc.13", path = "../../../macro/utils" }
