[package]
name = "iroha_config_derive"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", default-features = false, features = ["derive", "parsing", "proc-macro", "clone-impls", "printing"] }
# This is the maximally compressed set of features. Yes we also need "printing". 
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
