[package]
name = "iroha_permissions_validators"
version = "0.1.0"
authors = ["Egor Ivkov <e.o.ivkov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
roles = ["iroha_data_model/roles"]

[dependencies]
iroha_core = { path = "../iroha_core"}
iroha_data_model = { path = "../iroha_data_model" }
iroha_macro = { path = "../iroha_macro" }

[dev-dependencies]
maplit = "1.0.2"
