[package]
name = "iroha_client_cli"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha CLI Client provides an ability to interact with Iroha Peers Web API without direct network usage. It's a `light` client which only converts Command Line Interface commands into Iroha Web API Network Requests."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "client"]
categories = ["cryptography::cryptocurrencies", "command-line-utilities"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_client = { version = "=2.0.0-pre-rc.4", path = "../client" }
iroha_data_model = { version = "=2.0.0-pre-rc.4", path = "../data_model" }
iroha_crypto = { version = "=2.0.0-pre-rc.4", path = "../crypto" }

color-eyre = "0.5.11"
clap = { version = "3.1.10",  features = ["derive"] }
futures = { version = "0.3.17", default-features = false, features = ["std", "async-await"] }
dialoguer = { version = "0.9", default-features = false }
serde_json = "1.0"
