[package]
name = "iroha_client_cli"

edition.workspace = true
version.workspace = true
authors.workspace = true

description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

license.workspace = true
keywords.workspace = true
categories = ["cryptography::cryptocurrencies", "command-line-utilities"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_client = { version = "=2.0.0-pre-rc.13", path = "../client" }
iroha_data_model = { version = "=2.0.0-pre-rc.13", path = "../data_model" }
iroha_crypto = { version = "=2.0.0-pre-rc.13", path = "../crypto" }
iroha_config = { version = "=2.0.0-pre-rc.13", path = "../config" }

color-eyre = "0.6.2"
clap = { version = "3.2.23", features = ["derive"] }
dialoguer = { version = "0.10.2", default-features = false }
json5 = "0.4.1"
once_cell = "1.16.0"
serde_json = "1.0.93"
erased-serde = "0.3.24"

[build-dependencies]
eyre = "0.6.8"
vergen = { version = "7.3.2", default-features = false }
