[package]
name = "iroha_config"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[features]
# Support lightweight telemetry, including diagnostics
telemetry = []
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = ["telemetry"]

[dependencies]
iroha_config_base = { path = "base" }
iroha_data_model = { version = "=2.0.0-pre-rc.5", path = "../data_model" }
iroha_primitives = { version = "=2.0.0-pre-rc.5", path = "../primitives" }
iroha_crypto = { version = "=2.0.0-pre-rc.5", path = "../crypto" }
eyre = "0.6.5"
tracing = "0.1.13"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["fmt", "ansi"] }
url = { version = "2.2.2", features = ["serde"] }

serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
crossbeam = "0.8.1"
derive_more = "0.99.17"
