[package]
name = "iroha_logger"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_config = { workspace = true }
iroha_data_model = { workspace = true }

color-eyre = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-core = { workspace = true }
tracing-futures = { workspace = true, features = ["std-future", "std"] }
tracing-subscriber = { workspace = true, features = ["fmt", "ansi"] }
tracing-bunyan-formatter = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
console-subscriber =  { version = "0.1.8", optional = true }
once_cell = { workspace = true }
derive_more = { workspace = true }
tracing-error = "0.2.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "rt"] }


[features]
default = []
tokio-console = ["dep:console-subscriber", "tokio/tracing", "iroha_config/tokio-console"]
# Workaround to avoid activating `tokio-console` with `--all-features` flag, because `tokio-console` require `tokio_unstable` rustc flag
no-tokio-console = []
