[package]
name = "iroha_logger"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[dependencies]
iroha_config = { version = "=2.0.0-pre-rc.4", path = "../config" }

color-eyre = "0.5.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.13"
tracing-core = "0.1.13"
tracing-futures = { version = "0.2.5", default-features = false, features = ["std-future", "std"] }
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["fmt", "ansi"] }
tracing-bunyan-formatter = { version = "0.3.0", default-features = false }
tokio = { version = "1.6.0", features = ["sync"] }
once_cell = "1.8.0"

[dev-dependencies]
tokio = { version = "1.6.0", features = ["macros", "time", "rt"] }
