[package]
name = "iroha_permissions_validators"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
roles = ["iroha_core/roles"]

[dependencies]
iroha_core = { path = "../core"}
iroha_data_model = { path = "../data_model" }
iroha_macro = { path = "../macro" }
