[package]
name = "iroha_permissions_validators"
version = "2.0.0-pre-rc.3"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_core = { version = "=2.0.0-pre-rc.3", path = "../core", default-features = false }
iroha_data_model = { version = "=2.0.0-pre-rc.3", path = "../data_model", default-features = false }
iroha_macro = { version = "=2.0.0-pre-rc.3", path = "../macro" }

once_cell = "1.8.0"

[dev-dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.3", path = "../data_model", default-features = false }
iroha_core = { version = "=2.0.0-pre-rc.3", path = "../core", default-features = false }
