[package]
name = "iroha_schema_bin"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2018"


[dependencies]
iroha_schema = { path = "../../iroha_schema" }
iroha_data_model = { path = "../../iroha_data_model" }
iroha_core = { path = "../../iroha_core" }
eyre = "0.6.5"
serde_json = "1"
