[package]
name = "iroha_actor_derive"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.99"
quote = "1.0.21"
proc-macro2 = "1.0.43"
proc-macro-error = "1.0.4"

[dev-dependencies]
iroha_actor = { version = "=2.0.0-pre-rc.7", path = "../" }

trybuild = "1.0.64"
