[package]
name = "actor_derive"
version = "0.1.0"
authors = ["i1i1"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["parsing", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
