[package]
name = "iroha_trigger"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
# Enables debugging tools such as `dbg()` and `DebugUnwrapExt`
debug = ["iroha_wasm/debug"]

[dependencies]
iroha_wasm = { version = "2.0.0-pre-rc.18", path = ".." }
iroha_trigger_derive = { version = "2.0.0-pre-rc.18", path = "derive" }

[dev-dependencies]
webassembly-test.workspace = true
