[package]
name = "iroha_ffi_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true
categories = ["development-tools::ffi"]

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "visit", "visit-mut", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-error = { workspace = true }
derive_more = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
iroha_ffi = { workspace = true }

getset = { workspace = true }
trybuild = { workspace = true }
