[package]
name = "iroha_ffi_derive"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "visit", "visit-mut", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
iroha_ffi = { version = "=2.0.0-pre-rc.5", path = "../" }

getset = "0.1.2"
trybuild = "1.0.53"
