[package]
name = "iroha_ffi_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true
categories = ["development-tools::ffi"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.107", features = ["full", "visit", "visit-mut", "extra-traits"] }
quote = "1.0.23"
proc-macro2 = "1.0.49"
proc-macro-error = "1.0.4"
derive_more = "0.99.17"
rustc-hash = "1.1.0"

[dev-dependencies]
iroha_ffi = { version = "=2.0.0-pre-rc.16", path = "../" }

getset = "0.1.2"
trybuild = "1.0.73"
