## For the full reference, go to (TODO put link)

## You can use another TOML file to extend from.
## For a single file extension:
# extends = "./base.toml"
## Or, for a chain of extensions:
# extends = ["base-1.toml", "base-2.toml"]

# chain_id =
# public_key =
# private_key = {
#   algorithm = ,
#   payload =
# }

[genesis]
# file =
# public_key =
# private_key = { algorithm = "", payload = "" }

[network]
# address =
# block_gossip_period = "10s"
# block_gossip_max_size = 4
# transaction_gossip_period = "1s"
# transaction_gossip_max_size = 500
# idle_timeout = "60s"

[torii]
# address =
# max_content_len = "16mb"
# query_idle_time = "30s"

[kura]
# init_mode = "strict"
# store_dir = "./storage"

## Add more of this section for each trusted peer
# [[sumeragi.trusted_peers]]
# address =
# public_key =

[logger]
# level = "INFO"
# format = "full"

## Transactions Queue
[queue]
# capacity = 65536
# capacity_per_user = 65536
# transaction_time_to_live = "1day"
# future_threshold = "1s"

[snapshot]
# mode = "read_write"
# create_every = "1min"
# store_dir = "./storage/snapshot"

[telemetry]
# name =
# url =
# min_retry_period = "1s"
# max_retry_delay_exponent = 4

[dev_telemetry]
## A path to a file with JSON logs
# out_file = "./dev_telemetry.json"
