[package]
name = "iroha_derive"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0", features = ["parsing", "full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
iroha_macro = { path="../" }

parity-scale-codec = { version = "2", features = ["derive"] }
trybuild = "1.0.53"
