[package]
name = "kagami"
# Translates to teacher, the exemplar, the looking glass. A tool used to generate cryptographic keys, docs, the schema and genesis block.
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Explanation: You want the option to remove configuration docs if you
# distribute e.g. a `deb`, but want the person who just cloned the
# repo to be able to see at a glance what kinds of features are
# accessible to them, what they do and how to use them. #1975 should
# be fixed soon.
[features]
default = ["dex", "telemetry", "dev-telemetry"]
# Support Decentralised Exchange, including functionality for atomic exchange instruction
dex = ["iroha_core/dex"]
# Support lightweight telemetry, including diagnostics
telemetry = ["iroha_core/telemetry"]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = ["iroha_core/dev-telemetry"]


[dependencies]

iroha_core = { version = "=2.0.0-pre-rc.4", path = "../../core" }
iroha_crypto = { version = "=2.0.0-pre-rc.4", path = "../../crypto" }
iroha_config = { version = "=2.0.0-pre-rc.4", path = "../../config" }
iroha_data_model = { version = "=2.0.0-pre-rc.4", path = "../../data_model" }
iroha_schema_gen = { version = "=2.0.0-pre-rc.4", path = "../../schema/gen" }
iroha_schema = { version = "=2.0.0-pre-rc.4", path = "../../schema" }
iroha_permissions_validators = { version = "=2.0.0-pre-rc.4", path = "../../permissions_validators" }

iroha = { path = "../../cli" }

color-eyre = "0.5.11"
hex = "0.4.0"
clap = { version = "3.1.10",  features = ["derive"] }
serde_json = "1"
