[package]
name = "kagami"     # Translates to teacher, the exemplar, the looking glass.

edition.workspace = true
version.workspace = true
authors.workspace = true

description = "A tool used to generate cryptographic keys, docs, the schema and genesis block."

license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_crypto = { workspace = true }
iroha_config = { workspace = true }
iroha_data_model = { workspace = true }
iroha_schema_gen = { workspace = true }
iroha_primitives = { workspace = true }
iroha_genesis = { workspace = true }
test_samples = { workspace = true }

color-eyre = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, features = ["derive"] }
parity-scale-codec = { workspace = true }
