[package]
name = "kagami"     # Translates to teacher, the exemplar, the looking glass.

edition.workspace = true
version.workspace = true
authors.workspace = true

description = "A tool used to generate cryptographic keys, docs, the schema and genesis block."

license.workspace = true

[dependencies]
iroha_crypto = { workspace = true }
iroha_config = { workspace = true }
iroha_data_model = { workspace = true }
iroha_schema_gen = { workspace = true }
iroha_primitives = { workspace = true }
iroha_genesis = { workspace = true }
iroha_wasm_builder = { workspace = true }

color-eyre = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
expect-test = { workspace = true }
pathdiff = { workspace = true }
path-absolutize = { workspace = true }
spinoff = { workspace = true, features = ["aesthetic"] }
owo-colors = { workspace = true, features = ["supports-colors"] }
supports-color = { workspace = true }
inquire = { workspace = true }
duct = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
eyre = { workspace = true }
vergen = { workspace = true, features = ["git", "git2"] }
git2 = "0.17.2"
