[package]
name = "iroha_derive_primitives"
version = "2.0.0-pre-rc.19"
edition = "2021"

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits", "derive", "parsing"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
heck = "0.4.1"
