[package]
name = "iroha_derive_primitives"
version = "2.0.0-pre-rc.13"
edition = "2021"

[dependencies]
syn = { version = "1", default-features = false, features = ["full", "extra-traits", "derive", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0.49"
heck = "0.4.1"
