[package]
name = "iroha_version_derive"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = {version = "1", default-features = false, features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
iroha_version = { version = "=2.0.0-pre-rc.4", path = "..", features = ["scale", "json"]}
iroha_macro = { version = "=2.0.0-pre-rc.4", path = "../../macro" }

parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

trybuild = "1.0.53"
