[package]
name = "kura_inspector"
version = "2.0.0-pre-rc.3"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_core = { path = "../../core" }
iroha_config = { path = "../../config" }

clap = { version = "3.1.10", features = ["derive", "cargo"] }
futures-util = "0.3"
tokio = { version = "1.6.0", features = ["rt"]}

[dev-dependencies]
tempfile = "3"
