[package]
name = "kura_inspector"
version = "2.0.0-pre-rc.9"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_core = { path = "../../core" }
iroha_version = { path = "../../version" }

clap = { version = "3.2.16", features = ["derive", "cargo"] }
