[package]
name = "iroha"
version = "0.1.0"
authors = ["Nikita Puzankov <humb1t@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_derive = { path = "../iroha_macro/iroha_derive" }
iroha_network = { path = "../iroha_network" }
async-std = { version = "1.5", features = ["attributes"] }
futures = { version = "0.3.4", features = ["thread-pool"] }
parity-scale-codec = { version = "1.3", features = ["derive"] }
ursa = "0.3.2"

[dev-dependencies]
hex-literal = "0.2.1"
tempfile = "3"
