[package]
name = "iroha_crypto"
version = "2.0.0-pre-rc.9"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["ursa"]
# Force static linking
vendored = ["openssl-sys"]
# Replace structures and methods with FFI equivalents to facilitate dynamic linkage (mainly used in smartcontracts)
#ffi_import = []

# Expose FFI API for dynamic linking (Internal use only)
ffi_export = ["std"]

[dependencies]
iroha_primitives = { path = "../primitives", version = "=2.0.0-pre-rc.9", default-features = false }
iroha_ffi = { path = "../ffi", version = "=2.0.0-pre-rc.9" }
iroha_schema = { path = "../schema" }

derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "display"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.142", default-features = false, features = ["derive"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc", "serde"] }
openssl-sys = { version = "0.9.75", features = ["vendored"], optional = true }
ursa = { version = "0.3.7", optional = true }
getset = "0.1.2"

[dev-dependencies]
hex-literal = "0.3.4"
serde_json = "1.0.83"
