[package]
name = "iroha_crypto"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["ursa"]
# Force static linking
vendored = ["openssl-sys"]

[dependencies]
iroha_schema = { path = "../schema" }

derive_more = { version = "0.99.16", default-features = false, features = ["deref", "deref_mut", "display"] }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
hex = { version = "0.4.0", default-features = false, features = ["alloc", "serde"] }
openssl-sys = { version = "0.9.72", features = ["vendored"], optional = true }
ursa = { version = "=0.3.7", optional = true }
getset = "0.1.2"

[dev-dependencies]
hex-literal = "0.3.4"
serde_json = "1.0.59"
