[package]
name = "iroha_crypto"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["ursa"]
# Force static linking
vendored = ["openssl-sys"]
# Expose FFI API for dynamic linking (only applicable if crate-type = "cdylib")
ffi-export = ["std", "iroha_primitives/ffi-export"]
# Replace structures and methods with FFI equivalents to facilitate dynamic linkage (mainly used in smartcontracts)
#ffi-import = ["iroha_primitives/ffi-import"]

[dependencies]
iroha_primitives = { path = "../primitives", version = "=2.0.0-pre-rc.13", default-features = false }
iroha_ffi = { path = "../ffi", version = "=2.0.0-pre-rc.13" }
iroha_schema = { path = "../schema" }

derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "display"] }
parity-scale-codec = { version = "3.2.1", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0.151", default-features = false, features = ["derive"] }
serde_with = { version = "2.1.0", default-features = false, features = ["macros"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc", "serde"] }
openssl-sys = { version = "0.9.80", features = ["vendored"], optional = true }
ursa = { version = "0.3.7", optional = true }
getset = "0.1.2"

[dev-dependencies]
hex-literal = "0.3.4"
serde_json = "1.0.91"
