[package]
name = "test_network"
version = "0.1.0"
authors = ["i1i1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
unique_port = "0.1.0"
iroha = { path = "../../iroha" }
iroha_client = { path = "../../iroha_client" }
iroha_data_model = { path = "../../iroha_data_model" }
iroha_logger = { path = "../../iroha_logger" }
iroha_error = { path = "../../iroha_error" }
iroha_config = { path = "../../iroha_config" }
iroha_network = { path = "../../iroha_network", features = ["test-no-timeout"] }
async-std = { version = "=1.6.2", features = ["attributes"] }
rand = "0.7.3"
