name: Iroha MacOS

on:
  push:
    branches: [ main, support/1.2.x ]
  pull_request:
    branches: [ main, support/1.2.x ]

# strategy:
#   matrix:
#     cpp: [ g++-9, g++-10, clang++ ]
#     os: [ ubuntu-latest, ubuntu-18.04, ubuntu-16.04 ]
#     debrel: [ Debug ]
#     USE_LIBURSA: [ ON, OFF ]
#     USE_BURROW: [ ON, OFF ]
# strategy:
#   matrix:
#     cpp: [ clang++, /usr/local/opt/llvm/bin/clang++ ]  ##todo g++-10
#     os: [ macos-latest, macos-11.0, macos-10.15 ]
# strategy:
#   matrix:
#     cpp: [ /usr/local/opt/llvm/bin/clang++, ]
#     os: [ "windows-latest", "windows-2019", "windows-2016" ]

jobs:
  build-iroha-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        # cpp: [ clang++, /usr/local/opt/llvm/bin/clang++ ]  ##todo g++-10
        # os: [ macos-latest, macos-11.0, macos-10.15 ]
        USE_BURROW: [ -DUSE_BURROW=ON, -DUSE_BURROW=OFF ]
        debrel: [ Debug ] #,Release, RelWithDebInfo
    steps:
      - 
        name: Homebrew
        run: brew install cmake ninja coreutils
        ## ToDo cache installed packages or prepare image
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache vcpkg
        uses: actions/cache@v2
        with:
          path: |
            build-vcpkg
            build/vcpkg_installed
            $HOME/.cache/vcpkg
          key:          ${{ runner.os }}-vcpkg-${{ github.sha }}
          restore-keys: ${{ runner.os }}-vcpkg-
      - 
        name: Build Iroha vcpkg dependancies
        run: ./vcpkg/build_iroha_deps.sh $PWD/build-vcpkg
        # ________________________________________________________
        # Executed in   32,08 mins    fish           external
        #    usr time  110,52 mins    0,24 millis  110,52 mins
        #    sys time   12,26 mins    1,34 millis   12,26 mins
        # 
        # All requested packages are currently installed.
        # ________________________________________________________
        # Executed in    3,17 secs    fish           external
        #    usr time    2,05 secs  128,00 micros    2,05 secs
        #    sys time    0,70 secs  575,00 micros    0,70 secs
      - 
        name: CMake configure, vcpkg install
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$PWD/build-vcpkg/scripts/buildsystems/vcpkg.cmake
             ${{ matrix.USE_BURROW }} -GNinja #-DCMAKE_VERBOSE_MAKEFILE=ON
      -
        name: CMake build
        run: cmake --build build --config ${{ matrix.debrel }}
      -
        name: CTest
        run: |
          cd build
          ctest
