name: Build Docker-image iroha-builder

on:
  push:
    branches: [ main, support/1.2.x ]
    # paths: ['docker/**']
  pull_request:
    branches: [ main, support/1.2.x ]
    # paths: ['docker/**']

jobs:
  Build-Docker-image-iroha-builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/develop/Dockerfile.builder
          # context: .
          push: true
          tags: ikyb/iroha:builder
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  Build-vcpkg-dependancies:
    needs: Build-Docker-image-iroha-builder
    runs-on: ubuntu-latest
    container: ikyb/iroha:builder
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /opt/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
      - 
        name: Build Iroha dependancies
        run: |
          ./vcpkg/build_iroha_deps.sh /opt/vcpkg $PWD/vcpkg

  Build-iroha:
    needs: Build-vcpkg-dependancies
    runs-on: ubuntu-latest
    container: ikyb/iroha:builder
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /opt/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
      - 
        name: CMake Configure
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake #-DCMAKE_VERBOSE_MAKEFILE=ON
      -
        name: CMake build
        run: cmake --build build #--config
      -
        name: CTest
        run: |
          cd build
          ctest
