name: I2::Dev::Tests

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - "**.yml"

      # Not part of the workspace
      - "!wasm/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    if: ${{ false }}
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Documentation check
        if: always()
        run: |
          cargo doc --no-deps --quiet
          ./scripts/check.sh docs
      - name: Check genesis
        if: always()
        run: |
          ./scripts/check.sh genesis
      - name: Wasm build check
        if: always()
        env:
          RUSTC_BOOTSTRAP: 1
        working-directory: wasm
        run: mold --run cargo build --target wasm32-unknown-unknown --quiet

  # Coverage is both in PR and in push pipelines so that:
  # 1. PR can get coverage report from bot.
  # 2. Coverage bot can have results from `iroha2-dev` to report coverage changes.
  tests_with_coverage:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      # TODO Remove these steps #2165
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      #
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests and generate lcov report
        if: always()
        run: mold --run cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          file: lcov.info
          fail_ci_if_error: true

  integration_tests:
    if: ${{ false }}
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        if: always()
        run: |
          mold --run cargo test --test '*' --all-features -- \
          integration:: \
          --test-threads 2 \
          --skip unstable_network
