name: I2::Release::Deploy

on:
  push:
    branches: [iroha2]

env:
  CARGO_TERM_COLOR: always
  REPOSITORY_URL: '${{ github.server_url }}/${{ github.repository }}.git'

jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Build iroha2:build docker image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: iroha2:build
          context: ${{ env.REPOSITORY_URL }}#iroha2
          file: Dockerfile.build
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2:stable image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2:stable
          context: ${{ env.REPOSITORY_URL }}#iroha2
          file: Dockerfile

      - name: Build and push docker image (load-rs:release)
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-stable.yaml
          ref: master
