name: I2::Dev::Tests

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - '**.rs'
      - '**.json'
      - '**.toml'
      - '.github/workflows/**.yml'

      # Not part of the workspace
      - '!wasm/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: [self-hosted, Linux, iroha2ci]
    container:
      image: hyperledger/iroha2-planner:dev
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Check config.md
        if: always()
        run: ./scripts/check.sh docs
      - name: Check genesis.json
        if: always()
        run: ./scripts/check.sh genesis
      - name: Check client_cli/config.json
        if: always()
        run: ./scripts/check.sh client
      - name: Check schema.json
        if: always()
        run: ./scripts/check.sh schema
      - name: Wasm build check
        if: always()
        working-directory: wasm
        run: mold --run cargo +nightly-2022-08-15 build --target wasm32-unknown-unknown --quiet

  with_coverage:
    runs-on: [self-hosted, Linux, iroha2ci]
    container:
      image: hyperledger/iroha2-planner:dev
    strategy:
      matrix:
        feature_flag: [all-features, no-default-features]
    env:
      # TODO Set NIGHTLY in the container #2606
      NIGHTLY: nightly-2022-08-15
    steps:
      - uses: actions/checkout@v3
      # TODO Remove this step #2165
      - name: Adjust toolchain
        run: |
          rustup component add llvm-tools-preview
          rustup +$NIGHTLY component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Run tests, with ${{ matrix.feature_flag }}
        run: |
          mold --run cargo llvm-cov clean --workspace
          mold --run cargo +$NIGHTLY llvm-cov --doc --no-report --${{ matrix.feature_flag }} --workspace --no-fail-fast
          mold --run cargo llvm-cov --no-report --${{ matrix.feature_flag }} --workspace --no-fail-fast
      - name: Generate lcov report
        if: matrix.feature_flag == 'all-features'
        run: |
          # generate report without tests
          # https://github.com/taiki-e/cargo-llvm-cov#merge-coverages-generated-under-different-test-conditions
          mold --run cargo +$NIGHTLY llvm-cov --doctests --no-run --${{ matrix.feature_flag }} --workspace --lcov --output-path lcov.info
      - name: Upload coverage to coveralls.io
        if: matrix.feature_flag == 'all-features'
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: lcov.info
          git-branch: ${{ ${{ github.base_ref }}
          git-commit: ${{ github.event.pull_request.base.sha}}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  integration:
    runs-on: [self-hosted, Linux, iroha2ci]
    container:
      image: hyperledger/iroha2-planner:dev
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests, with no-default-features
        run: |
          mold --run cargo test --test mod --no-default-features -- \
          integration:: --skip unstable_network

  unstable:
    runs-on: [self-hosted, Linux, iroha2ci]
    container:
      image: hyperledger/iroha2-planner:dev
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: mold --run cargo test -p iroha_client --tests --no-default-features unstable_network --quiet
