name: I2::Tests::UI

on:
  pull_request:
    branches: [main, stable, lts]
    paths:
      - 'crates/*_derive/**.rs'
      - 'crates/*_macro*/**.rs'
      - '**/tests/ui.rs'
      - '**/tests/ui_*/**'
      - 'rust-toolchain.toml'
      - '.github/workflows/iroha2-pr-ui.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    timeout-minutes: 60
    strategy:
      matrix:
        feature_flag: [all-features, no-default-features]
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@nextest
      - name: Run UI tests, with ${{ matrix.feature_flag }}
        run: mold --run cargo nextest run --no-fail-fast  -E 'test(ui)' --${{ matrix.feature_flag }}
