name: I2::Tests::UI

on:
  pull_request:
    branches: [main, stable, iroha2-lts]
    paths:
      - '**/derive/**.rs'
      - '**/tests/ui.rs'
      - '**/tests/ui_*/**'
      - 'rust-toolchain.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2023-06-25
    timeout-minutes: 60
    strategy:
      matrix:
        feature_flag: [all-features, no-default-features]
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run tests, with ${{ matrix.feature_flag }}
        run: |
          mold --run cargo test --test ui --${{ matrix.feature_flag }}
