name: I2::Dev::BaseCoverage

on:
  pull_request:
    branches: [iroha2-dev]
    types: [closed]

jobs:
  with_artifact:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: iroha2-dev-pr.yml
          name: lcov-${{ github.event.pull_request.head.sha }}.info
          search_artifacts: true
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
