name: I2::Dev::Wasm

defaults:
  run:
    working-directory: wasm

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - 'wasm/**.rs'
      - 'wasm/**.json'
      - 'wasm/**.toml'
      - 'wasm/**.yml'
      - 'data_model/**.rs'
      - 'data_model/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTUP_TOOLCHAIN: nightly-2022-08-15

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check
      - name: Lints
        if: always()
        run: cargo lints clippy --workspace --benches --tests --examples --quiet
      - name: Documentation
        if: always()
        run: cargo doc --no-deps --quiet

  tests:
    runs-on: ubuntu-latest #[self-hosted, Linux]
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: mold --run cargo test --tests --quiet --no-fail-fast
