name: I2::Dev::Wasm

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - 'data_model/**.rs'
      - 'data_model/**.yml'
      - 'data_model/**.json'
      - 'data_model/**.toml'

      - 'smart_contract/**.rs'
      - 'smart_contract/**.yml'
      - 'smart_contract/**.json'
      - 'smart_contract/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTUP_TOOLCHAIN: nightly-2024-01-12

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-01-12
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install iroha_wasm_test_runner
        run: cargo install --path tools/wasm_test_runner
      - name: Run smart contract tests on WebAssembly VM
        working-directory: smart_contract
        run: mold --run cargo test --release --tests --target wasm32-unknown-unknown --no-fail-fast --quiet
