name: Iroha 2 main branch pull requests workflow

on:
  pull_request:
    branches: [iroha2]

env:
  CARGO_TERM_COLOR: always

jobs:
  long-tests:
    runs-on: ubuntu-latest
    container: rust:1.56-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            ca-certificates \
            clang \
            llvm-dev
      - name: Run long tests
        run: cargo test --workspace --verbose --no-fail-fast -- --ignored --test-threads=1 long

  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            ca-certificates \
            clang \
            llvm-dev
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56
      - name: Build Client CLI
        run: cargo build --verbose
        working-directory: client_cli
      - name: Setup docker test environment
        run: ./scripts/setup_docker_test_env.sh
      - name: Docker compose genesis test
        run: ./scripts/test_genesis_docker_compose.sh
      - name: Docker compose test
        run: ./scripts/test_docker_compose.sh
      - name: Cleanup docker test environment
        run: ./scripts/cleanup_docker_test_env.sh
