name: I2::Dev::Wasm

on:
  pull_request:
    branches: [main]
    paths:
      - 'crates/iroha_data_model/**.rs'
      - 'crates/iroha_data_model/**.yml'
      - 'crates/iroha_data_model/**.json'
      - 'crates/iroha_data_model/**.toml'

      - 'crates/iroha_smart_contract/**.rs'
      - 'crates/iroha_smart_contract/**.yml'
      - 'crates/iroha_smart_contract/**.json'
      - 'crates/iroha_smart_contract/**.toml'

      - 'crates/iroha_executor/**.rs'
      - 'crates/iroha_executor/**.yml'
      - 'crates/iroha_executor/**.json'
      - 'crates/iroha_executor/**.toml'

      - 'crates/iroha_trigger/**.rs'
      - 'crates/iroha_trigger/**.yml'
      - 'crates/iroha_trigger/**.json'
      - 'crates/iroha_trigger/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTUP_TOOLCHAIN: nightly-2024-09-09
  DOCKER_COMPOSE_PATH: defaults

jobs:
  build_executor:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build iroha executor
        run: cargo run --bin iroha_wasm_builder -- build ./wasm_samples/default_executor --optimize --out-file ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
      - name: Upload executor to reuse in other jobs
        uses: actions/upload-artifact@v4
        with:
          name: executor.wasm
          path: ${{ env.DOCKER_COMPOSE_PATH }}/executor.wasm
          retention-days: 1

  tests:
    runs-on: ubuntu-latest
    needs: build_executor
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Download executor.wasm file
        uses: actions/download-artifact@v4
        with:
          name: executor.wasm
          path: ${{ env.DOCKER_COMPOSE_PATH }}
      - name: Install iroha_wasm_test_runner
        run: cargo install --path iroha_wasm_test_runner
      - name: Run smart contract tests on WebAssembly VM
        working-directory: iroha_smart_contract
        run: mold --run cargo test -p iroha_smart_contract -p iroha_smart_contract_utils --release --tests --target wasm32-unknown-unknown --no-fail-fast --quiet
