name: Rust

on:
  push:
    branches: [ iroha2-dev ]
  pull_request:
    branches: [ iroha2-dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Format check
      run: cargo fmt -- --check
    - name: Static analysis
      run: cargo clippy -- -Dwarnings
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Build
      run: cargo build --verbose
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Run tests
      run: cargo test --verbose --no-fail-fast
    - name: Measure lines of code tests coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-v -- --skip=peer::tests::connect_three_peers --skip=add_asset --skip=client_can_transfer_asset_to_another_account --skip=single_threaded_async'
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
  test-network-mock:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Run network mock tests
      run: (cd ./iroha_network && cargo test --features mock)
    - name: Run iroha tests with network mock
      run: (cd ./iroha && cargo test --features network-mock)
  test-docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Build
      run: cargo build --verbose
    - name: Setup docker test environment
      run: ./scripts/setup_docker_test_env.sh
    - name: Docker compose test
      run: ./scripts/test_docker_compose.sh
    - name: Cleanup docker test environment
      run: ./scripts/cleanup_docker_test_env.sh
  bench:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Run benchmarks
      run: cargo bench
  docs:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Cache workspace target
      uses: actions/cache@v1
      env:
        cache-name: ${{ runner.os }}-cargo-build-target
      with:
        path: target
        key: workspace-target
    - name: Cache iroha target
      uses: actions/cache@v1
      env:
        cache-name: criterion-iroha-target
      with:
        path: iroha/target
        key: iroha-target
    - name: Documentation build
      run: cargo doc --no-deps -v
    - name: Archive documentation 
      uses: actions/upload-artifact@v1
      with:
        name: cargo-doc
        path: target/doc
