[package]
name = "iroha_data_primitives"
version = "2.0.0-pre-rc.4"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Data primitives used in iroha_data_model."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "model"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
# Enable static linkage of the rust standard library.
# Please refer to https://docs.rust-embedded.org/book/intro/no-std.html
std = ["iroha_macro/std", "fixnum/std", "thiserror"]

[dependencies]
iroha_macro = { path = "../../macro", version = "=2.0.0-pre-rc.4", default-features = false }
iroha_schema = { path = "../../schema", version = "=2.0.0-pre-rc.4", default-features = false }

parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
fixnum = { version = "0.6.1", default-features = false, features = ["serde", "parity", "i64"]}
derive_more = { version = "0.99.16", default-features = false, features = ["display"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
smallvec = { version = "1.8.0", default-features = false, features = ["serde", "union"] }
smallstr = { version = "0.3.0", default-features = false, features = ["serde", "union"] }
thiserror = { version = "1.0.28", optional = true }

[dev-dependencies]
serde_json = { version = "1.0.59", default-features = false, features = ["alloc"] }
